export const TEST_DATA = [
  {url: require('@/assets/images/korea1.jpeg'), id: 0},
  {url: require('@/assets/images/korea2.jpeg'), id: 1},
  {url: require('@/assets/images/korea3.jpeg'), id: 2},
  {url: require('@/assets/images/korea4.jpeg'), id: 3},
  {url: require('@/assets/images/korea5.jpeg'), id: 4},
  {url: require('@/assets/images/korea6.jpeg'), id: 5},
  {url: require('@/assets/images/korea7.jpeg'), id: 6},
  {url: require('@/assets/images/korea8.jpeg'), id: 7},
  {url: require('@/assets/images/korea9.jpeg'), id: 8},
  {url: require('@/assets/images/korea10.jpeg'), id: 9},
  {url: require('@/assets/images/korea11.jpeg'), id: 10},
  {url: require('@/assets/images/korea12.jpeg'), id: 11},
  {url: require('@/assets/images/korea13.jpeg'), id: 12},
  {url: require('@/assets/images/korea14.jpeg'), id: 13},
  {url: require('@/assets/images/korea15.jpeg'), id: 14},
  {url: require('@/assets/images/korea16.jpeg'), id: 15},
];
